#include "stdafx.h"
#include "LLookAndFeel.h"
#include "LookAndFeelParamWrapper.h"

void LLookAndFeel::wrapForLua (lua_State *L)
{
	using namespace luabind;
	LookAndFeelParamWrapper::wrapForLua(L);

	module(L)
	[
        class_<LLookAndFeel>("LLookAndFeel")
        ,
		class_<LookAndFeelBase, LLookAndFeel>("LookAndFeel")
			.def(constructor<>())
			.def ("findColour", &LLookAndFeel::findColour, &LLookAndFeel::def_findColour)
			.def ("setColour", &LLookAndFeel::setColour, &LLookAndFeel::def_setColour)
			.def ("isColourSpecified", &LLookAndFeel::isColourSpecified, &LLookAndFeel::def_isColourSpecified)
			.def ("getTypefaceForFont", &LLookAndFeel::getTypefaceForFont, &LLookAndFeel::def_getTypefaceForFont)
			.def ("getMouseCursorFor", &LLookAndFeel::getMouseCursorFor, &LLookAndFeel::def_getMouseCursorFor)
			.def ("drawButtonBackground", &LLookAndFeel::drawButtonBackground, &LLookAndFeel::def_drawButtonBackground)
			.def ("drawButtonText", &LLookAndFeel::drawButtonText, &LLookAndFeel::def_drawButtonText)
			.def ("drawToggleButton", &LLookAndFeel::drawToggleButton, &LLookAndFeel::def_drawToggleButton)
			.def ("changeToggleButtonWidthToFitText", &LLookAndFeel::changeToggleButtonWidthToFitText, &LLookAndFeel::def_changeToggleButtonWidthToFitText)
			.def ("drawTickBox", &LLookAndFeel::drawTickBox, &LLookAndFeel::def_drawTickBox)
			.def ("createAlertWindow", &LLookAndFeel::createAlertWindow, &LLookAndFeel::def_createAlertWindow)
			.def ("drawAlertBox", &LLookAndFeel::drawAlertBox, &LLookAndFeel::def_drawAlertBox)
			.def ("getAlertBoxWindowFlags", &LLookAndFeel::getAlertBoxWindowFlags, &LLookAndFeel::def_getAlertBoxWindowFlags)
			.def ("getAlertWindowButtonHeight", &LLookAndFeel::getAlertWindowButtonHeight, &LLookAndFeel::def_getAlertWindowButtonHeight)
			.def ("getAlertWindowMessageFont", &LLookAndFeel::getAlertWindowMessageFont, &LLookAndFeel::def_getAlertWindowMessageFont)
			.def ("getAlertWindowFont", &LLookAndFeel::getAlertWindowFont, &LLookAndFeel::def_getAlertWindowFont)
			.def ("drawProgressBar", &LLookAndFeel::drawProgressBar, &LLookAndFeel::def_drawProgressBar)
			.def ("drawSpinningWaitAnimation", &LLookAndFeel::drawSpinningWaitAnimation, &LLookAndFeel::def_drawSpinningWaitAnimation)
			.def ("areScrollbarButtonsVisible", &LLookAndFeel::areScrollbarButtonsVisible, &LLookAndFeel::def_areScrollbarButtonsVisible)
			.def ("getScrollbarEffect", &LLookAndFeel::getScrollbarEffect, &LLookAndFeel::def_getScrollbarEffect)
			.def ("getMinimumScrollbarThumbSize", &LLookAndFeel::getMinimumScrollbarThumbSize, &LLookAndFeel::def_getMinimumScrollbarThumbSize)
			.def ("getDefaultScrollbarWidth", &LLookAndFeel::getDefaultScrollbarWidth, &LLookAndFeel::def_getDefaultScrollbarWidth)
			.def ("getScrollbarButtonSize", &LLookAndFeel::getScrollbarButtonSize, &LLookAndFeel::def_getScrollbarButtonSize)
			.def ("getTickShape", &LLookAndFeel::getTickShape, &LLookAndFeel::def_getTickShape)
			.def ("getCrossShape", &LLookAndFeel::getCrossShape, &LLookAndFeel::def_getCrossShape)
			.def ("drawTreeviewPlusMinusBox", &LLookAndFeel::drawTreeviewPlusMinusBox, &LLookAndFeel::def_drawTreeviewPlusMinusBox)
			.def ("fillTextEditorBackground", &LLookAndFeel::fillTextEditorBackground, &LLookAndFeel::def_fillTextEditorBackground)
			.def ("drawTextEditorOutline", &LLookAndFeel::drawTextEditorOutline, &LLookAndFeel::def_drawTextEditorOutline)
			.def ("createCaretComponent", &LLookAndFeel::createCaretComponent, &LLookAndFeel::def_createCaretComponent)
			.def ("getDefaultFolderImage", &LLookAndFeel::getDefaultFolderImage, &LLookAndFeel::def_getDefaultFolderImage)
			.def ("getDefaultDocumentFileImage", &LLookAndFeel::getDefaultDocumentFileImage, &LLookAndFeel::def_getDefaultDocumentFileImage)
			.def ("createFileChooserHeaderText", &LLookAndFeel::createFileChooserHeaderText, &LLookAndFeel::def_createFileChooserHeaderText)
			.def ("drawFileBrowserRow", &LLookAndFeel::drawFileBrowserRow, &LLookAndFeel::def_drawFileBrowserRow)
			.def ("createFileBrowserGoUpButton", &LLookAndFeel::createFileBrowserGoUpButton, &LLookAndFeel::def_createFileBrowserGoUpButton)
			.def ("layoutFileBrowserComponent", &LLookAndFeel::layoutFileBrowserComponent, &LLookAndFeel::def_layoutFileBrowserComponent)
			.def ("drawBubble", &LLookAndFeel::drawBubble, &LLookAndFeel::def_drawBubble)
			.def ("drawLasso", &LLookAndFeel::drawLasso, &LLookAndFeel::def_drawLasso)
			.def ("drawPopupMenuBackground", &LLookAndFeel::drawPopupMenuBackground, &LLookAndFeel::def_drawPopupMenuBackground)
			.def ("drawPopupMenuItem", &LLookAndFeel::drawPopupMenuItem, &LLookAndFeel::def_drawPopupMenuItem)
			.def ("getPopupMenuFont", &LLookAndFeel::getPopupMenuFont, &LLookAndFeel::def_getPopupMenuFont)
			.def ("drawPopupMenuUpDownArrow", &LLookAndFeel::drawPopupMenuUpDownArrow, &LLookAndFeel::def_drawPopupMenuUpDownArrow)
			.def ("getIdealPopupMenuItemSize", &LLookAndFeel::getIdealPopupMenuItemSize, &LLookAndFeel::def_getIdealPopupMenuItemSize)
			.def ("getMenuWindowFlags", &LLookAndFeel::getMenuWindowFlags, &LLookAndFeel::def_getMenuWindowFlags)
			.def ("drawMenuBarBackground", &LLookAndFeel::drawMenuBarBackground, &LLookAndFeel::def_drawMenuBarBackground)
			.def ("getMenuBarItemWidth", &LLookAndFeel::getMenuBarItemWidth, &LLookAndFeel::def_getMenuBarItemWidth)
			.def ("getMenuBarFont", &LLookAndFeel::getMenuBarFont, &LLookAndFeel::def_getMenuBarFont)
			.def ("drawMenuBarItem", &LLookAndFeel::drawMenuBarItem, &LLookAndFeel::def_drawMenuBarItem)
			.def ("drawComboBox", &LLookAndFeel::drawComboBox, &LLookAndFeel::def_drawComboBox)
			.def ("getComboBoxFont", &LLookAndFeel::getComboBoxFont, &LLookAndFeel::def_getComboBoxFont)
			.def ("createComboBoxTextBox", &LLookAndFeel::createComboBoxTextBox, &LLookAndFeel::def_createComboBoxTextBox)
			.def ("positionComboBoxText", &LLookAndFeel::positionComboBoxText, &LLookAndFeel::def_positionComboBoxText)
			.def ("drawLabel", &LLookAndFeel::drawLabel, &LLookAndFeel::def_drawLabel)
			.def ("drawLinearSlider", &LLookAndFeel::drawLinearSlider, &LLookAndFeel::def_drawLinearSlider)
			.def ("drawLinearSliderBackground", &LLookAndFeel::drawLinearSliderBackground, &LLookAndFeel::def_drawLinearSliderBackground)
			.def ("drawLinearSliderThumb", &LLookAndFeel::drawLinearSliderThumb, &LLookAndFeel::def_drawLinearSliderThumb)
			.def ("getSliderThumbRadius", &LLookAndFeel::getSliderThumbRadius, &LLookAndFeel::def_getSliderThumbRadius)
			.def ("drawRotarySlider", &LLookAndFeel::drawRotarySlider, &LLookAndFeel::def_drawRotarySlider)
			.def ("createSliderButton", &LLookAndFeel::createSliderButton, &LLookAndFeel::def_createSliderButton)
			.def ("createSliderTextBox", &LLookAndFeel::createSliderTextBox, &LLookAndFeel::def_createSliderTextBox)
			.def ("getSliderEffect", &LLookAndFeel::getSliderEffect, &LLookAndFeel::def_getSliderEffect)
			.def ("getTooltipSize", &LLookAndFeel::getTooltipSize, &LLookAndFeel::def_getTooltipSize)
			.def ("drawTooltip", &LLookAndFeel::drawTooltip, &LLookAndFeel::def_drawTooltip)
			.def ("createFilenameComponentBrowseButton", &LLookAndFeel::createFilenameComponentBrowseButton, &LLookAndFeel::def_createFilenameComponentBrowseButton)
			.def ("layoutFilenameComponent", &LLookAndFeel::layoutFilenameComponent, &LLookAndFeel::def_layoutFilenameComponent)
			.def ("drawConcertinaPanelHeader", &LLookAndFeel::drawConcertinaPanelHeader, &LLookAndFeel::def_drawConcertinaPanelHeader)
			.def ("drawCornerResizer", &LLookAndFeel::drawCornerResizer, &LLookAndFeel::def_drawCornerResizer)
			.def ("drawResizableFrame", &LLookAndFeel::drawResizableFrame, &LLookAndFeel::def_drawResizableFrame)
			.def ("fillResizableWindowBackground", &LLookAndFeel::fillResizableWindowBackground, &LLookAndFeel::def_fillResizableWindowBackground)
			.def ("drawResizableWindowBorder", &LLookAndFeel::drawResizableWindowBorder, &LLookAndFeel::def_drawResizableWindowBorder)
			.def ("drawDocumentWindowTitleBar", &LLookAndFeel::drawDocumentWindowTitleBar, &LLookAndFeel::def_drawDocumentWindowTitleBar)
			.def ("createDocumentWindowButton", &LLookAndFeel::createDocumentWindowButton, &LLookAndFeel::def_createDocumentWindowButton)
			.def ("positionDocumentWindowButtons", &LLookAndFeel::positionDocumentWindowButtons, &LLookAndFeel::def_positionDocumentWindowButtons)
			.def ("getDefaultMenuBarHeight", &LLookAndFeel::getDefaultMenuBarHeight, &LLookAndFeel::def_getDefaultMenuBarHeight)
			.def ("createDropShadowerForComponent", &LLookAndFeel::createDropShadowerForComponent, &LLookAndFeel::def_createDropShadowerForComponent)
			.def ("drawGroupComponentOutline", &LLookAndFeel::drawGroupComponentOutline, &LLookAndFeel::def_drawGroupComponentOutline)
			.def ("getTabButtonSpaceAroundImage", &LLookAndFeel::getTabButtonSpaceAroundImage, &LLookAndFeel::def_getTabButtonSpaceAroundImage)
			.def ("getTabButtonOverlap", &LLookAndFeel::getTabButtonOverlap, &LLookAndFeel::def_getTabButtonOverlap)
			.def ("getTabButtonBestWidth", &LLookAndFeel::getTabButtonBestWidth, &LLookAndFeel::def_getTabButtonBestWidth)
			.def ("getTabButtonExtraComponentBounds", &LLookAndFeel::getTabButtonExtraComponentBounds, &LLookAndFeel::def_getTabButtonExtraComponentBounds)
			.def ("drawTabButton", &LLookAndFeel::drawTabButton, &LLookAndFeel::def_drawTabButton)
			.def ("drawTabButtonText", &LLookAndFeel::drawTabButtonText, &LLookAndFeel::def_drawTabButtonText)
			.def ("drawTabAreaBehindFrontButton", &LLookAndFeel::drawTabAreaBehindFrontButton, &LLookAndFeel::def_drawTabAreaBehindFrontButton)
			.def ("createTabButtonShape", &LLookAndFeel::createTabButtonShape, &LLookAndFeel::def_createTabButtonShape)
			.def ("fillTabButtonShape", &LLookAndFeel::fillTabButtonShape, &LLookAndFeel::def_fillTabButtonShape)
			.def ("createTabBarExtrasButton", &LLookAndFeel::createTabBarExtrasButton, &LLookAndFeel::def_createTabBarExtrasButton)
			.def ("drawImageButton", &LLookAndFeel::drawImageButton, &LLookAndFeel::def_drawImageButton)
			.def ("drawTableHeaderBackground", &LLookAndFeel::drawTableHeaderBackground, &LLookAndFeel::def_drawTableHeaderBackground)
			.def ("drawTableHeaderColumn", &LLookAndFeel::drawTableHeaderColumn, &LLookAndFeel::def_drawTableHeaderColumn)
			.def ("paintToolbarBackground", &LLookAndFeel::paintToolbarBackground, &LLookAndFeel::def_paintToolbarBackground)
			.def ("createToolbarMissingItemsButton", &LLookAndFeel::createToolbarMissingItemsButton, &LLookAndFeel::def_createToolbarMissingItemsButton)
			.def ("paintToolbarButtonBackground", &LLookAndFeel::paintToolbarButtonBackground, &LLookAndFeel::def_paintToolbarButtonBackground)
			.def ("paintToolbarButtonLabel", &LLookAndFeel::paintToolbarButtonLabel, &LLookAndFeel::def_paintToolbarButtonLabel)
			.def ("drawStretchableLayoutResizerBar", &LLookAndFeel::drawStretchableLayoutResizerBar, &LLookAndFeel::def_drawStretchableLayoutResizerBar)
			.def ("drawPropertyPanelSectionHeader", &LLookAndFeel::drawPropertyPanelSectionHeader, &LLookAndFeel::def_drawPropertyPanelSectionHeader)
			.def ("drawPropertyComponentBackground", &LLookAndFeel::drawPropertyComponentBackground, &LLookAndFeel::def_drawPropertyComponentBackground)
			.def ("drawPropertyComponentLabel", &LLookAndFeel::drawPropertyComponentLabel, &LLookAndFeel::def_drawPropertyComponentLabel)
			.def ("getPropertyComponentContentPosition", &LLookAndFeel::getPropertyComponentContentPosition, &LLookAndFeel::def_getPropertyComponentContentPosition)
			.def ("drawCallOutBoxBackground", &LLookAndFeel::drawCallOutBoxBackground, &LLookAndFeel::def_drawCallOutBoxBackground)
			.def ("drawLevelMeter", &LLookAndFeel::drawLevelMeter, &LLookAndFeel::def_drawLevelMeter)
			.def ("drawKeymapChangeButton", &LLookAndFeel::drawKeymapChangeButton, &LLookAndFeel::def_drawKeymapChangeButton)
	];
}
