#include "stdafx.h"
#include "LRectangle.h"

void LRectangle::wrapForLua (lua_State *L)
{
	using namespace luabind;

	module(L)
    [
		class_<Rectangle<int> >("Rectangle")
			.def(constructor<>())
			.def(constructor<const Rectangle<int> &>())
			.def(constructor<int,int,int,int>())
			.def(constructor<int,int>())
			.def(constructor<const Point<int> &, const Point <int> &>())
			.def("isEmpty", &Rectangle<int>::isEmpty)
			.def("getX", &Rectangle<int>::getX)
			.def("getY", &Rectangle<int>::getY)
			.def("getWidth", &Rectangle<int>::getWidth)
			.def("getHeight", &Rectangle<int>::getHeight)
			.def("getRight", &Rectangle<int>::getRight)
			.def("getBottom", &Rectangle<int>::getBottom)
			.def("getCentreX", &Rectangle<int>::getCentreX)
			.def("getCentreY", &Rectangle<int>::getCentreY)
			.def("getCentre", &Rectangle<int>::getCentre)
			.def("getAspectRatio", &Rectangle<int>::getAspectRatio)
			.def("getPosition", &Rectangle<int>::getPosition)
			.def("setPosition", (void (Rectangle<int>::*)(const Point<int> ) noexcept)&Rectangle<int>::setPosition)
			.def("setPosition", (void (Rectangle<int>::*)(const int, const int) noexcept)&Rectangle<int>::setPosition)
			.def("getTopLeft", &Rectangle<int>::getTopLeft)
			.def("getTopRight", &Rectangle<int>::getTopRight)
			.def("getBottomLeft", &Rectangle<int>::getBottomLeft)
			.def("getBottomRight", &Rectangle<int>::getBottomRight)
			.def("setSize", &Rectangle<int>::setSize)
			.def("setBounds", &Rectangle<int>::setBounds)
			.def("setX", &Rectangle<int>::setX)
			.def("setY", &Rectangle<int>::setY)
			.def("setWidth", &Rectangle<int>::setWidth)
			.def("setHeight", &Rectangle<int>::setHeight)
			.def("withX", &Rectangle<int>::withX)
			.def("withY", &Rectangle<int>::withY)
			.def("withPosition", (Rectangle<int> (Rectangle<int>::*)(const Point<int> ) const noexcept)&Rectangle<int>::withPosition)
			.def("withPosition", (Rectangle<int> (Rectangle<int>::*)(const int, const int) const noexcept)&Rectangle<int>::withPosition)
			.def("withZeroOrigin", &Rectangle<int>::withZeroOrigin)
			.def("withWidth", &Rectangle<int>::withWidth)
			.def("withHeight", &Rectangle<int>::withHeight)
			.def("withSize", &Rectangle<int>::withSize)
			.def("setLeft", &Rectangle<int>::setLeft)
			.def("withLeft", &Rectangle<int>::withLeft)
			.def("setTop", &Rectangle<int>::setTop)
			.def("withTop", &Rectangle<int>::withTop)
			.def("setRight", &Rectangle<int>::setRight)
			.def("withRight", &Rectangle<int>::withRight)
			.def("setBottom", &Rectangle<int>::setBottom)
			.def("withBottom", &Rectangle<int>::withBottom)
			.def("translate", &Rectangle<int>::translate)
			.def("translated", &Rectangle<int>::translated)
			.def("expand", &Rectangle<int>::expand)
			.def("expanded", (Rectangle<int> (Rectangle<int>::*)(const int, const int) const noexcept)&Rectangle<int>::expanded)
			.def("expanded", (Rectangle<int> (Rectangle<int>::*)(const int) const noexcept)&Rectangle<int>::expanded)
			.def("reduce", &Rectangle<int>::reduce)
			.def("reduced", (Rectangle<int> (Rectangle<int>::*)(const int, const int) const noexcept)&Rectangle<int>::reduced)
			.def("reduced", (Rectangle<int> (Rectangle<int>::*)(const int) const noexcept)&Rectangle<int>::reduced)
			.def("removeFromTop", &Rectangle<int>::removeFromTop)
			.def("removeFromLeft", &Rectangle<int>::removeFromLeft)
			.def("removeFromRight", &Rectangle<int>::removeFromRight)
			.def("removeFromBottom", &Rectangle<int>::removeFromBottom)
			.def("contains", (bool (Rectangle<int>::*)(const int, const int) const noexcept)&Rectangle<int>::contains)
			.def("contains", (bool (Rectangle<int>::*)(const Point<int> ) const noexcept)&Rectangle<int>::contains)
			.def("contains", (bool (Rectangle<int>::*)(const Rectangle<int> &) const noexcept)&Rectangle<int>::contains)
			.def("getConstrainedPoint", &Rectangle<int>::getConstrainedPoint)
			// .def("intersects", (bool (Rectangle<int>::*)(Rectangle<int> &) const noexcept) &Rectangle<int>::intersects)
			.def("getIntersection", &Rectangle<int>::getIntersection)
			.def("getUnion", &Rectangle<int>::getUnion)
			.def("enlargeIfAdjacent", &Rectangle<int>::enlargeIfAdjacent)
			.def("reduceIfPartlyContainedIn", &Rectangle<int>::reduceIfPartlyContainedIn)
			.def("transformedBy", &Rectangle<int>::transformedBy)
			.def("getSmallestIntegerContainer", &Rectangle<int>::getSmallestIntegerContainer)
			.def("toFloat", &Rectangle<int>::toFloat)
			.def("toString", &Rectangle<int>::toString)
			.def("leftTopRightBottom", &Rectangle<int>::leftTopRightBottom)
			.def("findAreaContainingPoints", &Rectangle<int>::findAreaContainingPoints)
			.def("intersectRectangles", &Rectangle<int>::intersectRectangles)
			.def("fromString", &Rectangle<int>::fromString)
		,
		class_<RectanglePlacement>("RectanglePlacement")
			.def(constructor<int>())
			.def("getFlags", &RectanglePlacement::getFlags)
			.def("testFlags", &RectanglePlacement::testFlags)
			.def("applyTo", &RectanglePlacement::applyTo)
			.enum_("flags")
			[
				value("xLeft", 1),
				value("xRight", 2),
				value("xMid", 4),
				value("yTop", 8),
				value("yBottom", 16),
				value("yMid", 32),
				value("stretchToFit", 64),
				value("fillDestination", 128),
				value("onlyReduceInSize", 256),
				value("onlyIncreaseInSize", 512),
				value("doNotResize", 768),
				value("centred", 36)
			]
    ,
        class_<LRectangle>("LRectangle")
    ,
        class_<Rectangle<float>, bases<LRectangle> >("RectangleFloat")
            .def(constructor<>())
            .def(constructor<const Rectangle<float> &>())
			.def(constructor<float,float,float,float>())
			.def(constructor<float,float>())
			.def(constructor<const Point<float> &, const Point <float> &>())
			.def("isEmpty", &Rectangle<float>::isEmpty)
			.def("getX", &Rectangle<float>::getX)
			.def("getY", &Rectangle<float>::getY)
			.def("getWidth", &Rectangle<float>::getWidth)
			.def("getHeight", &Rectangle<float>::getHeight)
			.def("getRight", &Rectangle<float>::getRight)
			.def("getBottom", &Rectangle<float>::getBottom)
			.def("getCentreX", &Rectangle<float>::getCentreX)
			.def("getCentreY", &Rectangle<float>::getCentreY)
			.def("getCentre", &Rectangle<float>::getCentre)
			.def("getAspectRatio", &Rectangle<float>::getAspectRatio)
			.def("getPosition", &Rectangle<float>::getPosition)
			.def("setPosition", (void (Rectangle<float>::*)(const Point<float> ) noexcept)&Rectangle<float>::setPosition)
			.def("setPosition", (void (Rectangle<float>::*)(const float, const float) noexcept)&Rectangle<float>::setPosition)
			.def("getTopLeft", &Rectangle<float>::getTopLeft)
			.def("getTopRight", &Rectangle<float>::getTopRight)
			.def("getBottomLeft", &Rectangle<float>::getBottomLeft)
			.def("getBottomRight", &Rectangle<float>::getBottomRight)
			.def("setSize", &Rectangle<float>::setSize)
			.def("setBounds", &Rectangle<float>::setBounds)
			.def("setX", &Rectangle<float>::setX)
			.def("setY", &Rectangle<float>::setY)
			.def("setWidth", &Rectangle<float>::setWidth)
			.def("setHeight", &Rectangle<float>::setHeight)
			.def("withX", &Rectangle<float>::withX)
			.def("withY", &Rectangle<float>::withY)
			.def("withPosition", (Rectangle<float> (Rectangle<float>::*)(const Point<float> ) const noexcept)&Rectangle<float>::withPosition)
			.def("withPosition", (Rectangle<float> (Rectangle<float>::*)(const float, const float) const noexcept)&Rectangle<float>::withPosition)
			.def("withZeroOrigin", &Rectangle<float>::withZeroOrigin)
			.def("withWidth", &Rectangle<float>::withWidth)
			.def("withHeight", &Rectangle<float>::withHeight)
			.def("withSize", &Rectangle<float>::withSize)
			.def("setLeft", &Rectangle<float>::setLeft)
			.def("withLeft", &Rectangle<float>::withLeft)
			.def("setTop", &Rectangle<float>::setTop)
			.def("withTop", &Rectangle<float>::withTop)
			.def("setRight", &Rectangle<float>::setRight)
			.def("withRight", &Rectangle<float>::withRight)
			.def("setBottom", &Rectangle<float>::setBottom)
			.def("withBottom", &Rectangle<float>::withBottom)
			.def("translate", &Rectangle<float>::translate)
			.def("translated", &Rectangle<float>::translated)
			.def("expand", &Rectangle<float>::expand)
			.def("expanded", (Rectangle<float> (Rectangle<float>::*)(const float, const float) const noexcept)&Rectangle<float>::expanded)
			.def("expanded", (Rectangle<float> (Rectangle<float>::*)(const float) const noexcept)&Rectangle<float>::expanded)
			.def("reduce", &Rectangle<float>::reduce)
			.def("reduced", (Rectangle<float> (Rectangle<float>::*)(const float, const float) const noexcept)&Rectangle<float>::reduced)
			.def("reduced", (Rectangle<float> (Rectangle<float>::*)(const float) const noexcept)&Rectangle<float>::reduced)
			.def("removeFromTop", &Rectangle<float>::removeFromTop)
			.def("removeFromLeft", &Rectangle<float>::removeFromLeft)
			.def("removeFromRight", &Rectangle<float>::removeFromRight)
			.def("removeFromBottom", &Rectangle<float>::removeFromBottom)
			.def("contains", (bool (Rectangle<float>::*)(const float, const float) const noexcept)&Rectangle<float>::contains)
			.def("contains", (bool (Rectangle<float>::*)(const Point<float> ) const noexcept)&Rectangle<float>::contains)
			.def("contains", (bool (Rectangle<float>::*)(const Rectangle<float> &) const noexcept)&Rectangle<float>::contains)
			.def("getConstrainedPoint", &Rectangle<float>::getConstrainedPoint)
			.def("getIntersection", &Rectangle<float>::getIntersection)
			.def("getUnion", &Rectangle<float>::getUnion)
			.def("enlargeIfAdjacent", &Rectangle<float>::enlargeIfAdjacent)
			.def("reduceIfPartlyContainedIn", &Rectangle<float>::reduceIfPartlyContainedIn)
			.def("transformedBy", &Rectangle<float>::transformedBy)
			.def("toString", &Rectangle<float>::toString)
			.def("leftTopRightBottom", &Rectangle<float>::leftTopRightBottom)
			.def("findAreaContainingPoints", &Rectangle<float>::findAreaContainingPoints)
			.def("intersectRectangles", &Rectangle<float>::intersectRectangles)
			.def("fromString", &Rectangle<float>::fromString)
			.def("toInt", &LRectangle::toInt)
	];
}
